platform :ios, '7.0'

pod 'AFNetworking',                 '~> 2.5.0' # Http网络请求
pod 'SSObject',                     '~> 1.4.0' # 对象序列化
pod 'MJExtension',					'~> 2.4.0' # 下拉刷新
pod 'JSONModel',                    '~> 1.1.0' # 键值对赋值到数据模型
pod 'ReactiveCocoa',                '~> 2.5.0' # 响应式编程框架
pod 'BlocksKit',                    '~> 2.2.0' # The Objective-C block utilities you always wish you had.
pod 'NSObjectExtend',               '~> 1.7.0' # NS系列类添加常用方法